"""
Train logistic regression model for custom dataset
Works with all_features_custom.pkl generated by run_ours_construct_mia_data_custom.py
"""

import pickle
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
import argparse
import os
import matplotlib.pyplot as plt


def get_model():
    """Return a logistic regression model"""
    clf = LogisticRegression(max_iter=5000, solver="liblinear")
    return clf


def train_model_single(
    x_train,
    x_test,
    y_train,
    y_test,
    n_components=10,
):
    """Train and evaluate logistic regression classifier"""
    scaler = MinMaxScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    # Train base model without PCA
    clf = get_model()
    clf.fit(x_train_scaled, y_train)
    pred_probs = clf.predict_proba(x_test_scaled)[:, 1]
    pred_probs_train = clf.predict_proba(x_train_scaled)[:, 1]
    
    all_auc_train = roc_auc_score(y_train, pred_probs_train)
    all_auc_test = roc_auc_score(y_test, pred_probs)

    fpr, tpr, _ = roc_curve(y_test, pred_probs)
    # Calculate TPR at FPR <= 0.01
    valid_indices = np.where(fpr <= 0.01)[0]
    if len(valid_indices) > 0:
        all_tpr = tpr[valid_indices[-1]] * 100
    else:
        all_tpr = 0.0
        
    fpr_train, tpr_train, _ = roc_curve(y_train, pred_probs_train)
    valid_indices_train = np.where(fpr_train <= 0.01)[0]
    if len(valid_indices_train) > 0:
        all_tpr_train = tpr_train[valid_indices_train[-1]] * 100
    else:
        all_tpr_train = 0.0

    all_results = {
        "auc_test": all_auc_test,
        "auc_train": all_auc_train,
        "tpr_test": all_tpr,
        "tpr_train": all_tpr_train,
        "fpr": fpr,
        "tpr": tpr,
        "fpr_train": fpr_train,
        "tpr_train": tpr_train,
        "pred_probs_test": pred_probs,
        "pred_probs_train": pred_probs_train,
    }

    # Train model with PCA
    if x_train.shape[1] >= n_components:
        pca = PCA(n_components=n_components)
        pca.fit(x_train)
        x_train_pca = pca.transform(x_train)
        x_test_pca = pca.transform(x_test)
        
        clf_pca = get_model()
        clf_pca.fit(x_train_pca, y_train)
        pred_probs_pca = clf_pca.predict_proba(x_test_pca)[:, 1]
        pred_probs_train_pca = clf_pca.predict_proba(x_train_pca)[:, 1]
        
        all_pca_train = roc_auc_score(y_train, pred_probs_train_pca)
        all_pca_test = roc_auc_score(y_test, pred_probs_pca)
        
        fpr_pca, tpr_pca, _ = roc_curve(y_test, pred_probs_pca)
        valid_indices_pca = np.where(fpr_pca <= 0.01)[0]
        if len(valid_indices_pca) > 0:
            all_pca_tpr = tpr_pca[valid_indices_pca[-1]] * 100
        else:
            all_pca_tpr = 0.0
            
        fpr_train_pca, tpr_train_pca, _ = roc_curve(y_train, pred_probs_train_pca)
        valid_indices_train_pca = np.where(fpr_train_pca <= 0.01)[0]
        if len(valid_indices_train_pca) > 0:
            all_pca_tpr_train = tpr_train_pca[valid_indices_train_pca[-1]] * 100
        else:
            all_pca_tpr_train = 0.0
        
        all_results["pca_auc_test"] = all_pca_test
        all_results["pca_auc_train"] = all_pca_train
        all_results["pca_tpr_test"] = all_pca_tpr
        all_results["pca_tpr_train"] = all_pca_tpr_train
        all_results["pca_model"] = clf_pca
        all_results["pca"] = pca
    
    all_results["model"] = clf
    all_results["scaler"] = scaler
    
    return all_results


def plot_roc_curve(fpr, tpr, auc, output_file="roc_curve_custom.png"):
    """Plot and save ROC curve"""
    plt.figure(figsize=(10, 8))
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {auc:.3f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random Classifier')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve - Custom Dataset')
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)
    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"ROC curve saved to {output_file}")
    plt.close()


def main():
    parser = argparse.ArgumentParser(description="Train LR on custom features")
    parser.add_argument(
        "--features_file",
        type=str,
        default="all_features_custom.pkl",
        help="Path to features pickle file from stage 1"
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./",
        help="Output directory for results"
    )
    parser.add_argument(
        "--test_split",
        type=float,
        default=0.2,
        help="Test set fraction (0.0-1.0)"
    )
    parser.add_argument(
        "--n_components",
        type=int,
        default=10,
        help="Number of PCA components"
    )
    parser.add_argument(
        "--random_seed",
        type=int,
        default=42,
        help="Random seed for reproducibility"
    )
    
    args = parser.parse_args()
    
    np.random.seed(args.random_seed)
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Load features
    print(f"Loading features from {args.features_file}...")
    if not os.path.exists(args.features_file):
        raise FileNotFoundError(f"Features file not found: {args.features_file}")
    
    with open(args.features_file, "rb") as f:
        data = pickle.load(f)
    
    member_preds = data["member_preds"]
    nonmember_preds = data["nonmember_preds"]
    
    print(f"Member samples: {len(member_preds)}")
    print(f"Non-member samples: {len(nonmember_preds)}")
    
    # Convert defaultdict predictions to feature vectors
    def extract_features_from_defaultdict(preds_list):
        """
        Convert list of defaultdicts to feature vectors by aggregating token probs.
        Each defaultdict has keys like 'tk_probs', 'labels', 'tk_probs_repeated_N', etc.
        We extract numerical features from these.
        """
        features = []
        for sample_dict in preds_list:
            sample_features = []
            
            # Process each key in the defaultdict
            for key, values in sorted(sample_dict.items()):
                if isinstance(values, list) and len(values) > 0:
                    try:
                        # Convert to numpy array
                        arr = np.array(values, dtype=float)
                        
                        # Flatten if needed
                        if len(arr.shape) > 1:
                            arr = arr.flatten()
                        
                        # Aggregate: mean, max, min, std
                        if len(arr) > 0:
                            sample_features.extend([
                                np.mean(arr),
                                np.max(arr),
                                np.min(arr),
                                np.std(arr) if len(arr) > 1 else 0.0,
                                len(arr),  # count
                            ])
                    except (ValueError, TypeError):
                        # Skip non-numeric values like 'labels'
                        continue
            
            if sample_features:
                features.append(sample_features)
        
        return np.array(features)
    
    print("Extracting features from defaultdicts...")
    x_member = extract_features_from_defaultdict(member_preds)
    x_nonmember = extract_features_from_defaultdict(nonmember_preds)
    
    print(f"Successfully converted to feature vectors")
    
    print(f"Member features shape: {x_member.shape}")
    print(f"Non-member features shape: {x_nonmember.shape}")
    
    # Create labels: 1 for member, 0 for non-member
    y_member = np.ones(len(x_member))
    y_nonmember = np.zeros(len(x_nonmember))
    
    # Combine data
    x_all = np.vstack([x_member, x_nonmember])
    y_all = np.hstack([y_member, y_nonmember])
    
    # Shuffle
    shuffle_idx = np.random.permutation(len(x_all))
    x_all = x_all[shuffle_idx]
    y_all = y_all[shuffle_idx]
    
    # Split into train and test
    split_point = int(len(x_all) * (1 - args.test_split))
    x_train = x_all[:split_point]
    x_test = x_all[split_point:]
    y_train = y_all[:split_point]
    y_test = y_all[split_point:]
    
    print(f"\nTrain set size: {len(x_train)} (members: {np.sum(y_train)}, non-members: {len(y_train) - np.sum(y_train)})")
    print(f"Test set size: {len(x_test)} (members: {np.sum(y_test)}, non-members: {len(y_test) - np.sum(y_test)})")
    
    # Train model
    print("\nTraining logistic regression model...")
    results = train_model_single(
        x_train,
        x_test,
        y_train,
        y_test,
        n_components=min(args.n_components, x_train.shape[1])
    )
    
    # Print results
    print("\n" + "="*50)
    print("MODEL EVALUATION RESULTS")
    print("="*50)
    print(f"Test AUC: {results['auc_test']:.4f}")
    print(f"Train AUC: {results['auc_train']:.4f}")
    print(f"Test TPR@FPR<=0.01: {results['tpr_test']:.2f}%")
    print(f"Train TPR@FPR<=0.01: {results['tpr_train']:.2f}%")
    
    if "pca_auc_test" in results:
        print(f"\nWith PCA ({args.n_components} components):")
        print(f"  Test AUC: {results['pca_auc_test']:.4f}")
        print(f"  Train AUC: {results['pca_auc_train']:.4f}")
        print(f"  Test TPR@FPR<=0.01: {results['pca_tpr_test']:.2f}%")
        print(f"  Train TPR@FPR<=0.01: {results['pca_tpr_train']:.2f}%")
    print("="*50)
    
    # Save model
    model_file = os.path.join(args.output_dir, "trained_model_custom.pkl")
    with open(model_file, "wb") as f:
        pickle.dump(results, f)
    print(f"\nModel saved to {model_file}")
    
    # Plot ROC curve
    roc_file = os.path.join(args.output_dir, "roc_curve_custom.png")
    plot_roc_curve(results['fpr'], results['tpr'], results['auc_test'], roc_file)
    
    # Save results summary
    results_file = os.path.join(args.output_dir, "results_summary_custom.txt")
    with open(results_file, "w") as f:
        f.write("="*50 + "\n")
        f.write("MODEL EVALUATION RESULTS\n")
        f.write("="*50 + "\n")
        f.write(f"Test AUC: {results['auc_test']:.4f}\n")
        f.write(f"Train AUC: {results['auc_train']:.4f}\n")
        f.write(f"Test TPR@FPR<=0.01: {results['tpr_test']:.2f}%\n")
        f.write(f"Train TPR@FPR<=0.01: {results['tpr_train']:.2f}%\n")
        if "pca_auc_test" in results:
            f.write(f"\nWith PCA ({args.n_components} components):\n")
            f.write(f"  Test AUC: {results['pca_auc_test']:.4f}\n")
            f.write(f"  Train AUC: {results['pca_auc_train']:.4f}\n")
            f.write(f"  Test TPR@FPR<=0.01: {results['pca_tpr_test']:.2f}%\n")
            f.write(f"  Train TPR@FPR<=0.01: {results['pca_tpr_train']:.2f}%\n")
        f.write("="*50 + "\n")
    print(f"Results summary saved to {results_file}")


if __name__ == "__main__":
    main()
